version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "monthly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
  
  - package-ecosystem: "pip"
    directory: "/app/"
    schedule:
      interval: "monthly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
