version: "3.7"
services:
  web:
    build: ./app
    container_name:
      job_history_web
    env_file:
      ./.env
    command:
      /usr/src/app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - job_history_net_1
    restart:
      "no"

networks:
  job_history_net_1:
