version: "3.7"
services:
  web:
    build: ./app
    container_name:
      job_history_web
    environment:
      - JOB_HISTORY_SECRET_KEY
      - JOB_HISTORY_DEBUG
      - JOB_HISTORY_ALLOWED_HOSTS
      - JOB_HISTORY_DB_NAME
      - JOB_HISTORY_STATIC_ROOT
      - JOB_HISTORY_STATIC_URL
    command:
      /usr/src/app/manage.py test
    ports:
      - "8000:8000"
    volumes:
      - "db_data:/data"
    networks:
      - job_history_net_1
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
    restart:
      "no"

networks:
  job_history_net_1:

volumes:
  db_data:
