version: '2'
jobs:
  build_and_test:
    working_directory: ~/job-history-circleci
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          mv docker-compose.circleci.yml docker-compose.yml
      - run: |
          docker-compose up --build --quiet-pull --exit-code-from=web --abort-on-container-exit
workflows:
  version: 2
  on_push:
    jobs:
      - build_and_test
