version: '2'
jobs:
  build_and_test:
    machine: true
    working_directory: ~/job-history-circleci
    steps:
      - checkout
      - run: |
          sudo pip install --upgrade pip
      - run: |
          sudo pip install docker-compose
      - run: |
          mv docker-compose.circleci.yml docker-compose.yml
      - run: |
          sudo docker-compose up --build --exit-code-from web --abort-on-container-exit
workflows:
  version: 2
  on_push:
    jobs:
      - build_and_test
