version: 2.1
jobs:
  build_and_test:
    machine: true
    working_directory: ~/job-history-circleci
    steps:
      - checkout
      - run: |
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run: |
          mv docker-compose.circleci.yml docker-compose.yml
      - run: |
          docker-compose up --build --exit-code-from web --abort-on-container-exit
workflows:
  version: 2
  on_push:
    jobs:
      - build_and_test
