[project]

project = "job-history"
dependencies = [
    "colorama>=0.4.6",
    "django>=4.2.14",
    "django-environ>=0.11.2",
    "lazy-object-proxy>=1.10.0",
    "pytz>=2024.1",
    "whitenoise>=6.7.0",
    "wrapt>=1.16.0",
]
