# Generated by Django 2.1.4 on 2019-01-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobtimeperiod',
            name='work_country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='position',
            name='supervisor_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='position',
            name='supervisor_country',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
