# Generated by Django 2.1.4 on 2019-01-05 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('long_name', models.CharField(max_length=254, null=True, unique=True)),
                ('industry', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('addr1', models.CharField(blank=True, max_length=200, verbose_name='Address Line 1')),
                ('addr2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('addr3', models.CharField(blank=True, max_length=200, verbose_name='Address Line 3')),
                ('city', models.CharField(max_length=200)),
                ('county_or_parish', models.CharField(blank=True, max_length=200)),
                ('state_or_province', models.CharField(blank=True, max_length=200)),
                ('zip_or_postal_code', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobTimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('start_month', models.PositiveSmallIntegerField(null=True)),
                ('start_day', models.PositiveSmallIntegerField(null=True)),
                ('is_current_position', models.BooleanField(default=True)),
                ('end_year', models.PositiveIntegerField(null=True)),
                ('end_month', models.PositiveSmallIntegerField(null=True)),
                ('end_day', models.PositiveSmallIntegerField(null=True)),
                ('starting_pay', models.CharField(max_length=50)),
                ('ending_pay', models.CharField(max_length=50)),
                ('hours_per_week', models.PositiveSmallIntegerField(null=True)),
                ('contributions_and_accomplishments', models.TextField(blank=True)),
                ('work_city', models.CharField(blank=True, max_length=200)),
                ('work_county_or_parish', models.CharField(blank=True, max_length=200)),
                ('work_state_or_province', models.CharField(blank=True, max_length=200)),
                ('work_zip_or_postal_code', models.CharField(blank=True, max_length=50)),
                ('work_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('responsibilities', models.TextField(blank=True)),
                ('contributions_and_accomplishments', models.TextField(blank=True)),
                ('supervisor_name_prefix', models.CharField(blank=True, max_length=50)),
                ('supervisor_given_name', models.CharField(max_length=200)),
                ('supervisor_middle_name', models.CharField(blank=True, max_length=200)),
                ('supervisor_surname', models.CharField(max_length=200)),
                ('supervisor_name_suffix', models.CharField(blank=True, max_length=50)),
                ('supervisor_phone', models.CharField(blank=True, max_length=50)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('supervisor_addr1', models.CharField(blank=True, max_length=200, verbose_name='Supervisor Address Line 1')),
                ('supervisor_addr2', models.CharField(blank=True, max_length=200, verbose_name='Supervisor Address Line 2')),
                ('supervisor_addr3', models.CharField(blank=True, max_length=200, verbose_name='Supervisor Address Line 3')),
                ('supervisor_city', models.CharField(max_length=200)),
                ('supervisor_county_or_parish', models.CharField(blank=True, max_length=200)),
                ('supervisor_state_or_province', models.CharField(blank=True, max_length=200)),
                ('supervisor_zip_or_postal_code', models.CharField(blank=True, max_length=50)),
                ('supervisor_country', models.CharField(max_length=200)),
                ('can_contact', models.BooleanField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobHistory.Employer')),
            ],
        ),
        migrations.AddField(
            model_name='jobtimeperiod',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobHistory.Position'),
        ),
    ]
