# Generated by Django 2.2.4 on 2019-08-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobHistory', '0003_auto_20190804_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Employer'},
        ),
        migrations.AlterModelOptions(
            name='jobtimeperiod',
            options={'verbose_name': 'Job Time Period'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Position'},
        ),
    ]
