# Generated by Django 2.2.15 on 2020-08-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHistory', '0005_auto_20200808_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtimeperiod',
            name='end_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Day'),
        ),
        migrations.AlterField(
            model_name='jobtimeperiod',
            name='end_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='End Month'),
        ),
        migrations.AlterField(
            model_name='jobtimeperiod',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='jobtimeperiod',
            name='hours_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hours per Week'),
        ),
        migrations.AlterField(
            model_name='jobtimeperiod',
            name='start_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Start Day'),
        ),
        migrations.AlterField(
            model_name='jobtimeperiod',
            name='start_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Start Month'),
        ),
    ]
