# Generated by Django 2.2.15 on 2020-08-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHistory', '0007_auto_20200813_1931'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employer',
            constraint=models.UniqueConstraint(fields=('short_name',), name='employer_must_be_unique'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('employer', 'title'), name='position_must_be_unique'),
        ),
    ]
