# Generated by Django 2.2.15 on 2020-08-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHistory', '0009_auto_20200821_2214'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobtimeperiod',
            name='job_time_period_must_be_unique',
        ),
        migrations.AddConstraint(
            model_name='jobtimeperiod',
            constraint=models.UniqueConstraint(fields=('position', 'start_year', 'is_current_position'), name='job_time_period_must_be_unique_1'),
        ),
        migrations.AddConstraint(
            model_name='jobtimeperiod',
            constraint=models.UniqueConstraint(condition=models.Q(is_current_position__exact=False), fields=('position', 'start_year', 'end_year'), name='job_time_period_start_and_end_year_must_be_unique_if_not_current_position'),
        ),
    ]
