# Generated by Django 2.2.15 on 2020-08-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobHistory', '0010_auto_20200821_2227'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobtimeperiod',
            name='job_time_period_must_be_unique_1',
        ),
        migrations.RemoveConstraint(
            model_name='jobtimeperiod',
            name='job_time_period_start_and_end_year_must_be_unique_if_not_current_position',
        ),
        migrations.AddConstraint(
            model_name='jobtimeperiod',
            constraint=models.UniqueConstraint(fields=('position', 'start_year', 'start_month', 'start_day', 'is_current_position'), name='job_time_period_must_be_unique_A'),
        ),
        migrations.AddConstraint(
            model_name='jobtimeperiod',
            constraint=models.UniqueConstraint(condition=models.Q(is_current_position__exact=False), fields=('position', 'start_year', 'start_month', 'start_day', 'end_year', 'end_month', 'end_day'), name='job_time_period_start_and_end_date_must_be_unique_if_not_current_position'),
        ),
    ]
